ALTER TABLE players DROP COLUMN active_character;
DROP TABLE hunt;
DROP TABLE enemies;
DROP TYPE enum_enemy;
DROP TABLE characters;
DROP TYPE enum_material;
DROP TABLE materials;
DROP TYPE enum_geartype;
DROP TABLE equipment;
DROP TABLE equipment_mods;
DROP TABLE players;